-- Note: Notwithstanding the license of the rest of this repository, I
-- (the author of this code) do not claim any copyright over this file.
-- The information contained herein, such as song titles, may or may not
-- be subject to copyright by its original authors. This information is
-- used nominally and without endorsement by these authors. To any extent
-- I would have copyright control over THIS PARTICULAR FILE, I relinquish
-- it to the public domain.
return {
  titles = {
    _default = { -- Default artist
      ["lobby"] = "Rhythmortis",
      ["training"] = "Watch Your Step",
      ["tutorial"] = "Tombtorial",
      ["zone ZONE_1 1"] = "Disco Descent",
      ["zone ZONE_1 2"] = "Crypteque",
      ["zone ZONE_1 3"] = "Mausoleum Mash",
      ["zone ZONE_2 1"] = "Fungal Funk",
      ["zone ZONE_2 2"] = "Grave Throbbing",
      ["zone ZONE_2 3"] = "Portabellohead",
      ["zone ZONE_3 1 c"] = "Stone Cold",
      ["zone ZONE_3 1 h"] = "Igneous Rock",
      ["zone ZONE_3 2 c"] = "Dance of the Decorus",
      ["zone ZONE_3 2 h"] = "March of the Profane",
      ["zone ZONE_3 3 c"] = "A Cold Sweat",
      ["zone ZONE_3 3 h"] = "A Hot Mess",
      ["zone ZONE_4 1"] = "Styx and Stones",
      ["zone ZONE_4 2"] = "Heart of the Crypt",
      ["zone ZONE_4 3"] = "The Wight to Remain",
      ["zone ZONE_5 1"] = "Voltzwaltz",
      ["zone ZONE_5 2"] = "Power Cords",
      ["zone ZONE_5 3"] = "Six Feet Thunder",
      ["boss KING_CONGA"] = "Konga Conga Kappa",
      ["boss DEATH_METAL"] = "Metalmancy",
      ["boss DEEP_BLUES"] = "Knight to C-Sharp",
      ["boss CORAL_RIFF"] = "Deep Sea Bass",
      ["boss FORTISSIMOLE"] = "Notorious D.I.G.",
      ["boss DEAD_RINGER"] = "For Whom the Knell Tolls",
      ["boss NECRODANCER"] = "Momentum Mori",
      ["boss NECRODANCER_2"] = "Momentum Mori (Melody ver.)",
      ["boss GOLDEN_LUTE"] = "Absolutetion",
      ["boss FRANKENSTEINWAY"] = "Steinway to Heaven",
      ["boss CONDUCTOR"] = "Vamplified",
      ["zone MageZone_MAGE_ZONE 1"] = "Runic Rumination",
      ["zone MageZone_MAGE_ZONE 2"] = "Occult Classic",
      ["zone MageZone_MAGE_ZONE 3"] = "Chaos in the Court",
      ["boss MageZone_SYMPHONY_OF_SORCERY"] = "Concerto Corporis",
      ["boss MageZone_SYMHPONY_OF_SORCERY"] = "Concerto Corporis" -- typo'd key in source mod
    },
    FAMILYJULES7X = {
      ["lobby"] = "Breath Before the Chaos",
      ["zone ZONE_1 1"] = "Infernal Descent",
      ["zone ZONE_1 2"] = "The Deranged",
      ["zone ZONE_1 3"] = "Spectral Storm",
      ["zone ZONE_2 1"] = "Blaze Hazard",
      ["zone ZONE_2 2"] = "Undead Desperation",
      ["zone ZONE_2 3"] = "Dark Means",
      ["zone ZONE_3 1 c"] = "Frozen in Panic",
      ["zone ZONE_3 1 h"] = "Scorched Volcanic",
      ["zone ZONE_3 2 c"] = "Anguish of the Frost",
      ["zone ZONE_3 2 h"] = "Heart of the Flame",
      ["zone ZONE_3 3 c"] = "A Glacial Death",
      ["zone ZONE_3 3 h"] = "A Dragon's Breath",
      ["zone ZONE_4 1"] = "Apex and Bones",
      ["zone ZONE_4 2"] = "Fury of the Crypt",
      ["zone ZONE_4 3"] = "A Shadow to Prevail",
      ["zone ZONE_5 1"] = "Tesla Toil",
      ["zone ZONE_5 2"] = "Power Corpse",
      ["zone ZONE_5 3"] = "Trial of Thunder",
      ["boss KING_CONGA"] = "Stronger Konga",
      ["boss DEATH_METAL"] = "Pyrodancer",
      ["boss DEEP_BLUES"] = "Knight Fall",
      ["boss CORAL_RIFF"] = "Deep Fear Octobass",
      ["boss FORTISSIMOLE"] = "Molevolence"
    },
    DANGANRONPA = {
      ["lobby"] = "DANGANRONPA",
      ["zone ZONE_1 1"] = "Last VERSUS",
      ["zone ZONE_1 2"] = "Junk Food for a Dashing Youth",
      ["zone ZONE_1 3"] = "Discussion -HEAT UP-",
      ["zone ZONE_2 1"] = "5th Island Theme",
      ["zone ZONE_2 2"] = "Wonderful Dead",
      ["zone ZONE_2 3"] = "Alice in the Children's Land",
      ["zone ZONE_3 1 c"] = "BOX 15",
      ["zone ZONE_3 1 h"] = "BOX 16",
      ["zone ZONE_3 2 c"] = "It's a Monokuma World",
      ["zone ZONE_3 2 h"] = "It's a Monokuma World",
      ["zone ZONE_3 3 c"] = "Supplementary Lessons for the Unlucky",
      ["zone ZONE_3 3 h"] = "Supplementary Lessons for the Mysterious",
      ["zone ZONE_4 1"] = "DISTRUST",
      ["zone ZONE_4 2"] = "Kill Command",
      ["zone ZONE_4 3"] = "Class Trial (Future Edition)",
      ["boss KING_CONGA"] = "Mr. Monokuma's Extracurricular Lesson",
      ["boss DEATH_METAL"] = "Monster That Shouts Its Love in the Center of Hell",
      ["boss DEEP_BLUES"] = "Punishment",
      ["boss CORAL_RIFF"] = "Trial Underground"
    },
    GROOVE_COASTER = {
      ["lobby"] = "Groove Prayer",
      ["zone ZONE_1 1"] = "Thrash Beat",
      ["zone ZONE_1 2"] = "I CANNOT APE",
      ["zone ZONE_1 3"] = "It's a pit world",
      ["zone ZONE_2 1"] = "Static Const Void",
      ["zone ZONE_2 2"] = "SKYSCRAPER",
      ["zone ZONE_2 3"] = "QLWA",
      ["zone ZONE_3 1 c"] = "Invader Disco",
      ["zone ZONE_3 1 h"] = "Invader Disco",
      ["zone ZONE_3 2 c"] = "BEFORE TEN ORB",
      ["zone ZONE_3 2 h"] = "BEFORE TEN ORB",
      ["zone ZONE_3 3 c"] = "VELVET",
      ["zone ZONE_3 3 h"] = "VELVET",
      ["zone ZONE_4 1"] = "Maiami Sound Remix",
      ["zone ZONE_4 2"] = "Five to Seven",
      ["zone ZONE_4 3"] = "Fess Up!",
      ["boss KING_CONGA"] = "カンナンシンク",
      ["boss DEATH_METAL"] = "Satisfaction",
      ["boss DEEP_BLUES"] = "FAKE (ALR Remix) (ダライアス外伝)",
      ["boss CORAL_RIFF"] = "Protocol Signal Generation"
    },
    HATSUNE_MIKU = {
      ["zone ZONE_1 1"] = "Too Real",
      ["zone ZONE_1 2"] = "Wonder Style",
      ["zone ZONE_1 3"] = "SURVIVE (Foxsky Remix)",
      ["zone ZONE_2 1"] = "Ten Thousand Stars",
      ["zone ZONE_2 2"] = "Lucky Orb (Clean Tears Remix)",
      ["zone ZONE_2 3"] = "UNDERWATER (Rexium Remix)",
      ["zone ZONE_3 1 c"] = "Highlight",
      ["zone ZONE_3 1 h"] = "Highlight",
      ["zone ZONE_3 2 c"] = "Intergalactic Bound",
      ["zone ZONE_3 2 h"] = "Intergalactic Bound",
      ["zone ZONE_3 3 c"] = "Hello Builder",
      ["zone ZONE_3 3 h"] = "Hello Builder",
      ["zone ZONE_4 1"] = "MikuFiesta",
      ["zone ZONE_4 2"] = "Can't Make A Song!!",
      ["zone ZONE_4 3"] = "Be Furious (Reno Remix)",
      ["zone ZONE_5 1"] = "sweety glitch",
      ["zone ZONE_5 2"] = "Thousand Little Voices",
      ["zone ZONE_5 3"] = "My One and Oni",
    }
  },
  artists = {
    _default = {
      _default = "Unknown artist"
    },
    _trackOverrides = {
      ["training"] = "Danny Baranowsky",
      ["tutorial"] = "Danny Baranowsky",
      ["boss DEAD_RINGER"] = "Danny Baranowsky",
      ["boss NECRODANCER"] = "Danny Baranowsky",
      ["boss NECRODANCER_2"] = "Danny Baranowsky",
      ["boss GOLDEN_LUTE"] = "Danny Baranowsky feat. FamilyJules",
      ["boss FRANKENSTEINWAY"] = "Danny Baranowsky",
      ["boss CONDUCTOR"] = "Danny Baranowsky",
      ["zone MageZone_MAGE_ZONE 1"] = "Creepslime",
      ["zone MageZone_MAGE_ZONE 2"] = "Creepslime",
      ["zone MageZone_MAGE_ZONE 3"] = "Creepslime",
      ["boss MageZone_SYMPHONY_OF_SORCERY"] = "Creepslime",
      ["boss MageZone_SYMHPONY_OF_SORCERY"] = "Creepslime" -- typo'd in source mod
    },
    DANNY_B = {
      _default = "Danny Baranowsky",
      ["zone ZONE_3 1 h"] = "Danny Baranowsky feat. FamilyJules",
      ["zone ZONE_3 2 h"] = "Danny Baranowsky feat. FamilyJules",
      ["zone ZONE_3 3 h"] = "Danny Baranowsky feat. FamilyJules",
      ["boss DEATH_METAL"] = "Danny Baranowsky feat. FamilyJules",
    },
    A_RIVAL = {
      _default = "A_Rival"
    },
    FAMILYJULES7X = {
      _default = "FamilyJules"
    },
    VIRT = {
      _default = "Jake Kaufman"
    },
    GIRLFRIEND_RECORDS = {
      _prefix = "Girlfriend Records - ",
      ["lobby"] = "Johnatron",
      ["zone ZONE_1 1"] = "Johnatron",
      ["zone ZONE_1 2"] = "Johnatron",
      ["zone ZONE_1 3"] = "Johnatron",
      ["zone ZONE_2 1"] = "Sferro",
      ["zone ZONE_2 2"] = "Sferro",
      ["zone ZONE_2 3"] = "Sferro",
      ["zone ZONE_3 1 c"] = "Sferro",
      ["zone ZONE_3 2 c"] = "Sferro",
      ["zone ZONE_3 3 c"] = "Sferro",
      ["zone ZONE_3 1 h"] = "Tommy '86",
      ["zone ZONE_3 2 h"] = "Tommy '86",
      ["zone ZONE_3 3 h"] = "Tommy '86",
      ["zone ZONE_4 1"] = "Tommy '86",
      ["zone ZONE_4 2"] = "Tommy '86",
      ["zone ZONE_4 3"] = "Tommy '86",
      ["zone ZONE_5 1"] = "Tommy '86",
      ["zone ZONE_5 2"] = "Sferro",
      ["zone ZONE_5 3"] = "Johnatron",
      ["boss KING_CONGA"] = "Johnatron",
      ["boss DEATH_METAL"] = "Sferro",
      ["boss DEEP_BLUES"] = "Johnatron",
      ["boss CORAL_RIFF"] = "Tommy '86",
      ["boss FORTISSIMOLE"] = "Johnatron",
      ["boss FORTISSIMOLE a"] = "Sferro",
      ["boss FORTISSIMOLE b"] = "Tommy '86"
    },
    OC_REMIX = {
      _prefix = "OC ReMix - ",
      ["lobby"] = "Flexstyle",
      ["zone ZONE_1 1"] = "DDRKirby(ISQ)",
      ["zone ZONE_1 2"] = "RoboRob",
      ["zone ZONE_1 3"] = "Chimpazilla",
      ["zone ZONE_2 1"] = "bLiNd",
      ["zone ZONE_2 2"] = "Phonetic Hero",
      ["zone ZONE_2 3"] = "Funk Fiction",
      ["zone ZONE_3 1 c"] = "Flexstyle feat. Nabeel Ansari",
      ["zone ZONE_3 1 h"] = "Sir_NutS",
      ["zone ZONE_3 2 c"] = "bLiNd",
      ["zone ZONE_3 2 h"] = "Kruai",
      ["zone ZONE_3 3 c"] = "bLiNd",
      ["zone ZONE_3 3 h"] = "Phonetic Hero",
      ["zone ZONE_4 1"] = "RoBKTA",
      ["zone ZONE_4 2"] = "Funk Fiction",
      ["zone ZONE_4 3"] = "Flextyle feat. DjjD",
      ["zone ZONE_5 1"] = "Chimpazilla",
      ["zone ZONE_5 2"] = "PrototypeRaptor",
      ["zone ZONE_5 3"] = "Funk Fiction",
      ["boss KING_CONGA"] = "RoboRob",
      ["boss DEATH_METAL"] = "Flexstyle",
      ["boss DEEP_BLUES"] = "James Landino",
      ["boss CORAL_RIFF"] = "ProrotypeRaptor",
      ["boss FORTISSIMOLE"] = "RoboRob"
    },
    CHIPZEL = {
      _default = "Chipzel"
    },
    DANGANRONPA = {
      _default = "Masafumi Takada",
      ["zone ZONE_5 1"] = "Danny Baranowsky",
      ["zone ZONE_5 2"] = "Danny Baranowsky",
      ["zone ZONE_5 3"] = "Danny Baranowsky",
      ["boss FORTISSIMOLE"] = "Danny Baranowsky"
    },
    GROOVE_COASTER = {
      _default = "COSIO",
      ["lobby"] = "COSIO feat. ChouCho",
      ["zone ZONE_2 2"] = "Dr. ARM (IOSYS)",
      ["zone ZONE_2 3"] = "t+pazolite",
      ["zone ZONE_3 3 c"] = "Massive New Krew",
      ["zone ZONE_3 3 h"] = "Massive New Krew",
      ["zone ZONE_4 1"] = "Mitsuto Suzuki",
      ["boss DEATH_METAL"] = "t+pazolite",
      ["zone ZONE_5 1"] = "Tommy '86",
      ["zone ZONE_5 2"] = "Sferro",
      ["zone ZONE_5 3"] = "Johnatron",
      ["boss FORTISSIMOLE"] = "Johnatron"
    },
    HATSUNE_MIKU = {
      _suffix = " & Hatsune Miku",
      _default = "Danny Baranowsky",
      ["zone ZONE_1 2"] = "colatte",
      ["zone ZONE_1 3"] = "Umetora",
      ["zone ZONE_2 1"] = "CircusP",
      ["zone ZONE_2 2"] = "emon(Tes.)",
      ["zone ZONE_2 3"] = "Hylen",
      ["zone ZONE_3 1 c"] = "KIRA",
      ["zone ZONE_3 1 h"] = "KIRA",
      ["zone ZONE_3 2 c"] = "CircusP & Yunosuke",
      ["zone ZONE_3 2 h"] = "CircusP & Yunosuke",
      ["zone ZONE_3 3 c"] = "UtsuP",
      ["zone ZONE_3 3 h"] = "UtsuP",
      ["zone ZONE_4 1"] = "AlexTrip Sands",
      ["zone ZONE_4 2"] = "beat_shobon",
      ["zone ZONE_4 3"] = "Ocelot",
      ["zone ZONE_5 1"] = "gaburyu & nyankobrq",
      ["zone ZONE_5 2"] = "Vaultt Kid & FlangerMoose",
    }
  },
  vocals = {
    _tracks = {
      ["boss FORTISSIMOLE"] = {
        _default = "Mega Ran"
      }
    }
  }
}